### ISSUE TITLE
OpenHUE-CLI make generate error  : oapi-gencode missing

### ISSUE THREAD

**Issue by jmma59** [openhue/openhue-cli#47]
Hi,
I am trying to discover your openhue-CLI tools. I have folowed discribed procedure to deploy localy.

During install I have mistake : 

Requirement : OK
- Golang   (V1.22.1)
- Goreleaser
- Docker (25.0.3)

Download openhue-cli  OK
- git clone     OK
- cd <local directory>
- make build    OK
- make test     OK
- make coverage OK   
- make generate NOK
error message

```bash
make generate
Code generation from https://api.redocly.com/registry/bundle/openhue/openhue/v2/openapi.yaml?branch=main

/bin/sh: 1: oapi-codegen: not found
make: *** [Makefile:24 : generate] Erreur 127
```

Could you help me please ?
Have a nice day

**Comment by thibauult** [comment]
Hi @jmma59, 

Thanks for opening this issue! 

The `make generate` command requires to install [oapi-codegen](https://github.com/deepmap/oapi-codegen) tool. Can you please try to install it using: 

```shell
go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@latest
```

and then try again to the `make generate` command? 

If it works I will update the project README accordingly.

**Comment by thibauult** [comment]
Fixed by https://github.com/openhue/openhue-cli/pull/58
