### ISSUE TITLE
Installation error - make command

### ISSUE THREAD

**Issue by DomTranch** [openhue/openhue-cli#56]
Hello, 
I am trying to install openhue-cli to try and control a standard Phillips Hue bridge with more control than is given in the standard app. I am currently trying to install on a Kali Linux machine and am running into the following error after following the tutorial:
![image](https://github.com/openhue/openhue-cli/assets/169126008/840c4750-04ec-463b-82d9-b1cf9c0c4d7c)
the  [Makefile:30: build] Error 127 output was not initally helpful for troubleshooting. Additionally, based on what the help command is giving me, I should expect an executable in the ./dist folder, but that's not in the current directory. Is there anything that I missed in downloading that would alleviate the issue? Is there something else that I'm missing in the instructions? Any guidance would be helpful.

**Comment by thibauult** [comment]
Hi @DomTranch, could you please verify if you've installed [GoReleaser](https://goreleaser.com/install)?

**Comment by DomTranch** [comment]
Yes, that indeed fixed it. Thank you! For anyone else, these are the specific lines that I ran (and apologies for any command line issues, I can't GitHub well):
echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
sudo apt update
sudo apt install goreleaser
After that,
make build
ran without error. Definitely recommend GoReleaser as a required tool.

**Comment by thibauult** [comment]
Thanks @DomTranch for confirming that it is now working well. 

Documentation has been fixed as part of https://github.com/openhue/openhue-cli/pull/58, and I also introduced an additional check in the `Makefile` to verify that GoReleaser in available before running the `make build` command.
